forms:
  myorg-issue:
    path: /myorg/myorg-credential
    type: issue-credential
    schema_name: myorg-credential.my-organization.ca
    page_title: My Organization Credential Issuer
    title: Issue Sample Credentials
    template: bcgov.index.html
    description: >
      Test Credential Issuer ... TBD.
    explanation: Use the form below to issue credentials for an existing corporation.

    js_includes:
      - src: js/bc_registries.js

    proof_request:
      id: registration
      connection_id: bctob

    fields:
      - name: corp_num
        label: Company Number
        type: text
        required: true
      - name: credential_status
        label: Credential Status
        type: select
        options:
          - ACT
          - HIS
        required: true
      - name: credential_status_effective
        label: Credential Effecive Date
        type: date
        required: true
      - name: credential_status_expiry
        label: Credential Expiry Date
        type: date
        required: false

    mapping:
      attributes:
        - name: effective_date
          from: helper
          source: now
