- name: myorg-credential.my-organization.ca
  version: '1.0.0'
  attributes:
    corp_num:
      description: Unique identifer assigned to entity by registrar (requires an existing registration credential)
      required: Y
    credential_status:
      description: Status of the credential (ACTive or HIStorical)
      required: Y
    credential_status_effective:
      description: Date status became/becomes effective (e.g. can be future dated)
      required: Y
    credential_status_expiry:
      description: Date status will expire
      required: N
    effective_date:
      description: Date Credential is effective (typically same as date credential is issued)
      required: Y
