default:
  APPLICATION_URL_VONX: $APPLICATION_URL/myorg/myorg-credential
  TEMPLATE_PATH: ../templates
  TOB_API_URL: http://tob-api:8080/api/v2
  TOB_APP_URL: http://localhost:8080
  WALLET_SEED_VONX: bc_von_x_dev_0000000000000000000
  # Example parameters to connect to a Sovrin ledger
  #INDY_GENESIS_URL: https://raw.githubusercontent.com/sovrin-foundation/sovrin/1.1.50-master/sovrin/pool_transactions_sandbox_genesis
  #LEDGER_PROTOCOL_VERSION: "1.3"
  #AUTO_REGISTER_DID: 0
