issuers:
  myorg:
    name: My Test Organization
    abbreviation: myorg
    url: https://www2.gov.bc.ca/gov/issuer-info-page
    email: TBD@gov.bc.ca
    logo_path: ../assets/img/tbd-logo.jpg
    endpoint: $ENDPOINT_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      name: ${POSTGRESQL_WALLET_NAME:-myorg_issuer}
      seed: $WALLET_SEED_VONX
      type: $WALLET_TYPE
      params:
        storage_config:
          url: "$POSTGRESQL_WALLET_HOST:$POSTGRESQL_WALLET_PORT"
      access_creds:
        key: $WALLET_ENCRYPTION_KEY
        storage_credentials:
          account: $POSTGRESQL_WALLET_USER
          password: $POSTGRESQL_WALLET_PASSWORD
          admin_account: ${POSTGRESQL_WALLET_ADMIN_USER:-postgres}
          admin_password: $POSTGRESQL_WALLET_ADMIN_PASSWORD
        key_derivation_method: ARGON2I_MOD

    credential_types:
      - description: Registration
        schema: myorg-registration.ian_company.ca
        issuer_url: $ENDPOINT_URL/myorg/incorporation
        # define credential meta-data
        # maps attributes provided in the credential to TOB's credential effective and revoked dates
        # if not provided TOB will set effective and expiry dates based on current date
        credential:
          effective_date:
            input: effective_date
            from: claim
          revoked_date:
            input: expiry_date
            from: claim
        # identifies the organization id that owns the credential
        # "topic" is used as a more generic term since the platform can be used for entities other than organizations
        # in our deployment the type is always "registration"
        topic:
          source_id:
            input: registration_id
            from: claim
          type:
            input: registration
            from: value
        # optional - specify additional cardinality fields
        #cardinality_fields:
        #  - additionl_cred_type_attr
        # mapping to the TOB data model - can map to name, address or a generic attribute
        mapping:
          # "name" is a known mapping; "legal_name" is a known field name
          - model: name
            fields:
              text:
                input: legal_name
                from: claim
              type:
                input: legal_name
                from: value
          # "address" is a known mapping; it maps to many fields in the model
          - model: address
            fields:
              addressee:
                input: addressee
                from: claim
              civic_address:
                input: address_line_1
                from: claim
              city:
                input: city
                from: claim
              province:
                input: province
                from: claim
              postal_code:
                input: postal_code
                from: claim
              country:
                input: country
                from: claim
          # "attribute" defines a generic field in the TOB model
          # "value" identifies where to derive the data value (typically it comes from the claim)
          # "type" - if "value" - is the name of the attribute
          # "format" is an optional data format (default text)
          - model: attribute
            fields:
              type:
                input: registration_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: registration_date
                from: claim
          - model: attribute
            fields:
              type:
                input: entity_type
                from: value
              value:
                input: entity_type
                from: claim
          - model: attribute
            fields:
              type:
                input: entity_status
                from: value
              value:
                input: entity_status
                from: claim
          - model: attribute
            fields:
              type:
                input: entity_status_effective
                from: value
              format:
                input: datetime
                from: value
              value:
                input: entity_status_effective
                from: claim
          - model: attribute
            fields:
              type:
                input: entity_name_effective
                from: value
              format:
                input: datetime
                from: value
              value:
                input: entity_name_effective
                from: claim
          - model: attribute
            fields:
              type:
                input: effective_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: effective_date
                from: claim
          - model: attribute
            fields:
              type:
                input: expiry_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: expiry_date
                from: claim

      - description: Tax Number
        schema: myorg-tax.ian_company.ca
        issuer_url: $ENDPOINT_URL/myorg/tax
        depends_on:
          - registration
        credential:
          effective_date:
            input: effective_date
            from: claim
        topic:
          source_id:
            input: registration_id
            from: claim
          type:
            input: registration
            from: value
        #cardinality_fields:
        #  - associated_registration_id
        mapping:
          - model: attribute
            fields:
              text:
                input: tax_number
                from: claim
              type:
                input: tax_number
                from: value
          - model: attribute
            fields:
              type:
                input: effective_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: effective_date
                from: claim

      - description: Liquor License
        schema: myorg-liquor.ian_company.ca
        issuer_url: $ENDPOINT_URL/myorg/liquor
        depends_on:
          - registration
        credential:
          effective_date:
            input: effective_date
            from: claim
          revoked_date:
            input: expiry_date
            from: claim
        topic:
          source_id:
            input: registration_id
            from: claim
          type:
            input: registration
            from: value
        mapping:
          - model: attribute
            fields:
              text:
                input: license_number
                from: claim
              type:
                input: license_number
                from: value
          - model: attribute
            fields:
              type:
                input: dancing_permitted
                from: value
              value:
                input: dancing_permitted
                from: claim
          - model: attribute
            fields:
              type:
                input: patio
                from: value
              value:
                input: patio
                from: claim
          - model: attribute
            fields:
              type:
                input: effective_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: effective_date
                from: claim
          - model: attribute
            fields:
              type:
                input: expiry_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: expiry_date
                from: claim

      - description: Test Credential
        schema: myorg-credential.ian_company.ca
        issuer_url: $ENDPOINT_URL/myorg/myorg-credential
        depends_on:
          - liquor_and_tax
        credential:
          effective_date:
            input: effective_date
            from: claim
          inactive:
            input: credential_status
            from: claim
            processor:
              - bcgov.entity_status.is_historical
          revoked_date:
            input: expiry_date
            from: claim
        topic:
          source_id:
            input: registration_id
            from: claim
          type:
            input: registration
            from: value
        mapping:
          - model: category
            fields:
              type:
                input: credential_status
                from: value
              value:
                input: credential_status
                from: claim
          - model: attribute
            fields:
              type:
                input: credential_status_effective
                from: value
              format:
                input: datetime
                from: value
              value:
                input: credential_status_effective
                from: claim
          - model: attribute
            fields:
              type:
                input: credential_status_expiry
                from: value
              format:
                input: datetime
                from: value
              value:
                input: credential_status_expiry
                from: claim
          - model: attribute
            fields:
              type:
                input: effective_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: effective_date
                from: claim
          - model: attribute
            fields:
              type:
                input: expiry_date
                from: value
              format:
                input: datetime
                from: value
              value:
                input: expiry_date
                from: claim

#################################################################
# TODO insert new service here, note should align like:
#   credential_types:
#     - description: Registration
      - description: Describes the credential - depends on permitifys foundation credential
        schema: todo-rename-me1.ian_company.ca
        issuer_url: $ENDPOINT_URL/myorg/todo-credential1
        depends_on:
        - permitify_registration
        credential:
          effective_date:
            input: effective_date
            from: claim
          revoked_date:
            input: expiry_date
            from: claim
        topic:
          source_id:
            input: corp_num
            from: claim
          type:
            input: registration
            from: value
        mapping:
        - model: attribute
          fields:
            type:
              input: corp_num
              from: value
            value:
              input: corp_num
              from: claim
        - model: attribute
          fields:
            type:
              input: credential_id
              from: value
            value:
              input: credential_id
              from: claim
        - model: attribute
          fields:
            type:
              input: credential_text
              from: value
            value:
              input: credential_text
              from: claim
        - model: attribute
          fields:
            type:
              input: credential_status
              from: value
            value:
              input: credential_status
              from: claim
        - model: attribute
          fields:
            type:
              input: effective_date
              from: value
            format:
              input: datetime
              from: value
            value:
              input: effective_date
              from: claim
        - model: attribute
          fields:
            type:
              input: expiry_date
              from: value
            format:
              input: datetime
              from: value
            value:
              input: expiry_date
              from: claim
              
      - description: Describes the credential - depends on myorg foundation credential
        schema: todo-rename-me3.ian_company.ca
        issuer_url: $ENDPOINT_URL/myorg/todo-credential3
        depends_on:
        - registration
        credential:
          effective_date:
            input: effective_date
            from: claim
        topic:
          source_id:
            input: registration_id
            from: claim
          type:
            input: registration
            from: value
        cardinality_fields:
        - credential_subtype
        mapping:
        - model: attribute
          fields:
            type:
              input: registration_id
              from: value
            value:
              input: registration_id
              from: claim
        - model: attribute
          fields:
            type:
              input: credential_id
              from: value
            value:
              input: credential_id
              from: claim
        - model: attribute
          fields:
            type:
              input: credential_subtype
              from: value
            value:
              input: credential_subtype
              from: claim
        - model: attribute
          fields:
            type:
              input: credential_text
              from: value
            value:
              input: credential_text
              from: claim
        - model: attribute
          fields:
            type:
              input: credential_status
              from: value
            value:
              input: credential_status
              from: claim
        - model: attribute
          fields:
            type:
              input: effective_date
              from: value
            format:
              input: datetime
              from: value
            value:
              input: effective_date
              from: claim

#################################################################

verifiers:
  bctob:
    name: BC OrgBook
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
    wallet:
      seed: "tob-verifier-wallet-000000000001"

proof_requests:
  registration:
    version: '1.0.0'
    schemas:
      - key:
          did: UAQM8wzfoLtzPemFDisgCo
          name: myorg-registration.ian_company.ca
          version: '1.0.0'
        attributes:
          - registration_id
          - legal_name
  liquor_and_tax:
    version: '1.0.0'
    schemas:
      - key:
          did: UAQM8wzfoLtzPemFDisgCo
          name: myorg-registration.ian_company.ca
          version: '1.0.0'
        attributes:
          - registration_id
          - legal_name
      - key:
          did: UAQM8wzfoLtzPemFDisgCo
          name: myorg-tax.ian_company.ca
          version: '1.0.0'
        attributes:
          - tax_number
      - key:
          did: UAQM8wzfoLtzPemFDisgCo
          name: myorg-liquor.ian_company.ca
          version: '1.0.0'
        attributes:
          - license_number
  bcreg_registration:
    version: '1.0.1'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: registration.registries.ca
          version: '1.0.38'
        attributes:
          - registration_id
  permitify_registration:
    version: '1.0.2'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: registration.dflow
          version: '1.0.0'
        attributes:
          - corp_num
  permitify_operating_permit:
    version: '1.0.2'
    schemas:
      - key:
          did: L6SJy7gNRCLUp8dV94hfex
          name: operating_permit.dflow
          version: '1.0.0'
        attributes:
          - corp_num
